# Generated by Django 5.1.5 on 2025-01-14 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('speakers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='speakerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speakeravailability',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='speakers.speakerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='speakeravailability',
            unique_together={('speaker', 'date', 'start_time', 'end_time')},
        ),
    ]
